#
# Copyright 2023 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "call_sim"
version = "0.1.0"
authors = ["Calling Team <callingteam@signal.org>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.81"
bollard = "0.15.0"
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
futures-core = "0.3.30"
futures-util = "0.3.30"
hound = "3.5.1"
itertools = "0.12.1"
plotly = { version = "0.8.4", features = ["kaleido"] }
prost = "0.12.3"
regex = "1.10.4"
relative-path = "1.9.2"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros", "time", "fs", "process"] }
tonic = "0.11.0"
tower = "0.4.13"

[build-dependencies]
tonic-build = "0.11.0"
