#
# Copyright 2023 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "call_sim"
version = "0.1.0"
authors = ["Calling Team <callingteam@signal.org>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0"
bollard = "0.15.0"
chrono = "0.4"
clap = { version = "4.4.11", features = ["derive"] }
futures-core = "0.3.29"
futures-util = "0.3.29"
hound = "3.5"
itertools = "0.12.0"
plotly = { version = "0.8.3", features = ["kaleido"] }
prost = "0.12.3"
regex = "1.10.2"
relative-path = "1.7.2"
serde_json = "1.0.108"
tokio = { version = "1.34.0", features = ["rt-multi-thread", "macros", "time", "fs", "process"] }
tonic = "0.10.2"
tower = "0.4"

[build-dependencies]
tonic-build = "0.10.2"
