#
# Copyright 2019-2021 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[package]
name = "ringrtc"
version = "2.33.0"
authors = ["Calling Team <callingteam@signal.org>"]
edition = "2021"
description = "A Rust interface for WebRTC"
license = "AGPL-3.0-only"

[lib]
crate_type = ["cdylib", "staticlib", "lib"]

[[bin]]
name = "direct"
required-features = ["native", "simnet"]

[[bin]]
name = "group_call"
required-features = ["native", "http"]

[[bin]]
name = "call_link"
# This binary doesn't depend on WebRTC at all, so either `sim` or `native` would work.
required-features = ["sim", "http", "rand_chacha"]

[[bin]]
name = "call_sim-cli"
required-features = ["call_sim"]

[dependencies]
regex-aot         = { path = "regex-aot" }

aes               = { version = "0.7.5"  }
aes-gcm-siv       = { version = "0.10.3" }
anyhow            = { version = "1.0"    }
base64            = { version = "0.21.3" }
bytes             = { version = "1.0"    }
ctr               = { version = "0.8"    }
futures           = { version = "0.3"    }
hmac              = { version = "0.11"   }
lazy_static       = { version = "1.4"    }
libc              = { version = "0.2"    }
log               = { version = "0.4", features = ["std", "max_level_trace", "release_max_level_info"] }
num_enum          = { version = "0.7.0" }
prost             = { version = "0.11"   }
rand              = { version = "0.7", features = [] }
regex-automata    = { version = "0.1.10" }
hkdf              = { version = "0.11"   }
serde_json        = { version = "1.0"    }
serde             = { version = "1.0", features = ["derive"] }
serde_with        = { version = "2.3.2", features = ["base64", "hex"] }
hex               = { version = "0.4", features = ["serde"] }
sha2              = { version = "0.9.9"  }
static_assertions = { version = "1.1.0"  }
subtle            = { version = "2.4.1"  }
thiserror         = { version = "1.0.47" }
x25519-dalek      = { version = "1.2"    }

# Used by call links. Be careful not to pull in more than strictly needed, for both code size and
# maintenance reasons. In particular, anything involving credentials should be left to
# libsignal-client.
bincode = { version = "1.2.1" }
zkgroup = { git = "https://github.com/signalapp/libsignal", tag = "v0.23.1" }

# Optional, needed by the "electron" feature
neon = { version = "0.10.1", optional = true, default-features = false, features = ["napi-6", "channel-api", "try-catch-api"] }

# Optional, needed to check Android-specific code when not targeting Android
jni = { version = "0.19.0", optional = true, default-features = false }

# Optional, needed by the "http" feature
ureq = { version = "2.7.1", optional = true }
rustls = { version = "0.21.6", optional = true, features = ["dangerous_configuration"] }
webpki = { version = "0.22", optional = true }

# Optional, needed for call-link-test-client
rand_chacha = { version = "0.2", optional = true }

# Optional, needed by the "call_sim" feature
chrono = {version = "0.4", optional = true }
clap = { version = "4.4.2", optional = true, features = ["derive"] }
fern = { version = "0.6", optional = true }
tonic = { version = "0.9.2", optional = true }
tokio = { version = "1.32.0", optional = true, features = ["rt-multi-thread"] }
tower = { version = "0.4", optional = true }

[target.'cfg(not(target_os="android"))'.dependencies]
# sysinfo depends on getgrgid_r, which was added in Android API level 24
sysinfo = { version = "0.29.10", default-features = false }

[features]
default = []
sim = []
electron = ["neon", "native"]
native = []  # We have this so we can more easily disable things only native clients need
simnet = []  # We have this so we can more easily disable things only simulated native client need
http = ["ureq", "rustls", "webpki"]
check-all = ["electron", "jni"]
call_sim = ["native", "chrono", "clap", "fern", "tokio", "tonic", "tower"]

[[test]]
name = "incoming"
path = "tests/incoming.rs"
required-features = ["sim"]

[[test]]
name = "outgoing"
path = "tests/outgoing.rs"
required-features = ["sim"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19.0", default-features = false }

[build-dependencies]
prost-build = { version = "0.11" }
tonic-build = { version = "0.9.2" }

[dev-dependencies]
env_logger = { version = "0.10" }
rand_chacha = { version = "0.2" }

[patch.crates-io]
# Use our fork of curve25519-dalek for zkgroup compatibility.
curve25519-dalek = { git = 'https://github.com/signalapp/curve25519-dalek', branch = 'lizard2' }
