# rustfmt for ringrtc

license_template_path        = "rustfmt.license-template"
unstable_features            = true

ignore = [
       # Don't format the generated protobuf code
       "src/protobuf",
]
