name: Build

on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space in runner
      uses: ./.github/actions/disk-cleanup

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Build Docker image
      run: docker build -f Dockerfile.android -t ringrtc-builder .

    - name: Build library inside Docker
      run: |
        docker run \
          -v ringrtc:/ringrtc \
          -v "$HOME/.gradle/caches:/.gradle-ro-cache:ro" \
          ringrtc-builder --release-build

    - name: Publish to GitHub Packages
      if: "github.ref_type == 'tag'"
      run: |
        docker run \
          -v ringrtc:/ringrtc \
          -v "$HOME/.gradle/caches:/.gradle-ro-cache:ro" \
          -e GITHUB_TOKEN \
          ringrtc-builder --release-build --publish
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_PAT }}

    - name: Clean up Docker
      if: always()
      run: docker container prune -f
