name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Install protoc
      run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /opt/depot_tools
        cd /opt/depot_tools
        git checkout "$DEPOT_TOOLS_GIT_HASH^{commit}"
        echo "/opt/depot_tools" >> "$GITHUB_PATH"
      env:
        DEPOT_TOOLS_GIT_HASH: 3f3e2f789e27d41d3c20a555fd60a39ebd631e15

    - name: Install Rust targets
      run: rustup toolchain install $(cat rust-toolchain) --profile minimal --target aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android

    - name: Prepare workspace for Android
      run: bin/prepare-workspace android
      env:
        DEPOT_TOOLS_UPDATE: 0

    - name: Build library
      run: bin/build-aar --arch arm arm64 x64 --release-build
      env:
        OVERRIDE_VERSION: ${{ github.ref_name }}

    - name: Log checksums
      run: find out/release/libs -type f -exec sha256sum '{}' +

    - name: Upload AARs
      uses: actions/upload-artifact@v3
      with:
        name: libs
        path: out/release/libs/

    - name: Publish to GitHub Packages
      run: ./bin/build-aar --arch arm arm64 x64 --release-build --publish
      env:
        OVERRIDE_VERSION: ${{ github.ref_name }}
        GITHUB_TOKEN: ${{ secrets.PUBLISH_PAT }}
