name: Release

on:
  pull_request:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    name: Build & Release
    environment: cloudsmith
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space in runner
      uses: ./.github/actions/disk-cleanup

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: true

    - name: Build Docker image
      run: docker build -f Dockerfile.android -t ringrtc-builder .

    - name: Build and publish to Cloudsmith
      run: |
        docker run \
          -v "$HOME/.gradle/caches:/.gradle-ro-cache:ro" \
          -e CLOUDSMITH_USER \
          -e CLOUDSMITH_API_KEY \
          ringrtc-builder --release-build --publish
      env:
        CLOUDSMITH_USER: ${{ secrets.CLOUDSMITH_USER }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
