name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Free up disk space
      run: sudo rm -rf /usr/share/dotnet /opt/ghc

    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@master

    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /opt/depot_tools
        cd /opt/depot_tools
        git checkout "$DEPOT_TOOLS_GIT_HASH^{commit}"
        echo "/opt/depot_tools" >> "$GITHUB_PATH"
      env:
        DEPOT_TOOLS_GIT_HASH: f537138fb7019fc321cbda339c8ce4599499af8e

    - name: Install Clippy
      run: rustup component add clippy

    - name: Install Rust targets
      run: rustup target add armv7-linux-androideabi aarch64-linux-android x86_64-linux-android

    - name: Prepare workspace for Android
      run: ./bin/prepare-workspace android
      env:
        DEPOT_TOOLS_UPDATE: 0

    - name: Accept all SDK licenses
      run: yes | src/webrtc/src/third_party/android_sdk/public/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build library
      run: ./bin/build-aar --arch arm arm64 x64 --release-build
      env:
        ORG_GRADLE_PROJECT_ci: 1

    - name: Log checksums
      run: sha256sum out/gradle/outputs/aar/*

    - name: Upload AARs
      uses: actions/upload-artifact@v2
      with:
        name: ringrtc-aar
        path: out/gradle/outputs/aar

    - name: Publish to GitHub Packages
      run: ./bin/build-aar --arch arm arm64 x64 --release-build --publish
      env:
        ORG_GRADLE_PROJECT_ci: 1
        GITHUB_TOKEN: ${{ secrets.PUBLISH_PAT }}
