name: RingRTC CI
on:
  push:
    branches: [ master, 'staging/*' ]
  pull_request: # all target branches

jobs:
  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt
    - name: Check format
      run: cd src/rust && cargo fmt -- --check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: clippy
    - run: rm -rf out/rust-lint
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --target-dir=out/rust-lint --manifest-path=./src/rust/Cargo.toml --features sim -- -D warnings
    - run: rustup target add aarch64-linux-android aarch64-apple-ios
    - name: Clippy (Android)
      run: cargo clippy --target aarch64-linux-android -- -D warnings
      working-directory: src/rust
      env:
        # Must be set to something, but will be ignored for check/clippy
        OUTPUT_DIR: out
    - name: Clippy (iOS)
      run: cargo clippy --target aarch64-apple-ios -- -D warnings
      working-directory: src/rust
      env:
        # Must be set to something, but will be ignored for check/clippy
        OUTPUT_DIR: out
    - name: Clippy (Electron)
      run: cargo clippy --features electron -- -D warnings
      working-directory: src/rust
      env:
        # Must be set to something, but will be ignored for check/clippy
        OUTPUT_DIR: out

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
    - name: Run rust tests
      run: cd src/rust && ./scripts/run-tests
