name: Sync Upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  sync_ringrtc:
    name: Sync RingRTC
    runs-on: ubuntu-latest

    outputs:
      webrtc-version: ${{ steps.set.outputs.webrtc-version }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: upstream
          fetch-depth: 0
          token: ${{ secrets.SYNC_PAT }}

      - run: git remote add upstream https://github.com/signalapp/ringrtc.git
      - run: git pull --ff-only upstream main
      - run: git push origin upstream

      - name: Output WebRTC version
        id: set
        run: |
          ver=$(grep '^webrtc.version=' config/version.properties | cut -d'=' -f2)
          echo "webrtc-version=$ver" >> $GITHUB_OUTPUT

  update_webrtc_tag:
    name: Update WebRTC Version
    runs-on: ubuntu-latest
    needs: sync_ringrtc

    env:
      WEBRTC_VERSION: ${{ needs.sync_ringrtc.outputs.webrtc-version }}

    steps:
      - name: Checkout WebRTC
        uses: actions/checkout@v4
        with:
          repository: mollyim/webrtc
          token: ${{ secrets.SYNC_PAT }}

      - run: git remote add upstream https://github.com/signalapp/webrtc.git
      - run: git fetch --tags upstream
      - run: git push origin "$WEBRTC_VERSION"
