name: Sync upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  sync:
    name: Sync
    if: "github.repository_owner == 'mollyim'"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: upstream
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_PAT }}

      - name: Fetch and merge upstream
        run: |
          git remote add upstream https://github.com/signalapp/ringrtc.git
          git fetch upstream
          git merge --ff-only upstream/main

      - name: Push changes
        run: |
          git push origin upstream
          git tag | grep -xP 'v\d+(?:\.\d+){2,3}' | xargs -r git push origin
