name: Test

on:
  pull_request: # all target branches
  push: # all target branches
    paths-ignore:
      - '**/README*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt
    - name: Check rust format
      run: cargo fmt -- --check
      working-directory: src/rust
    - name: Install for node
      run: yarn install --frozen-lockfile
      working-directory: src/node
    - name: Check typescript format
      run: yarn format -c
      working-directory: src/node

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: clippy
    - run: shellcheck **/*.sh bin/build-aar bin/build-cli bin/build-electron bin/build-gctc bin/build-ios bin/build-javadoc bin/build-rustdoc bin/build-target bin/fetch-android-deps bin/gsync-webrtc bin/prepare-workspace bin/rust-lint-check src/rust/scripts/run-tests
    - run: rm -rf out/rust-lint
    - name: Run clippy
      run: cargo clippy --target-dir=out/rust-lint --manifest-path=./src/rust/Cargo.toml --features sim -- -D warnings
    - run: rustup target add aarch64-linux-android aarch64-apple-ios
    - name: Clippy (Android)
      run: cargo clippy --target aarch64-linux-android -- -D warnings
      working-directory: src/rust
    - name: Clippy (iOS)
      run: cargo clippy --target aarch64-apple-ios -- -D warnings
      working-directory: src/rust
    - name: Clippy (Electron)
      run: cargo clippy --features electron -- -D warnings
      working-directory: src/rust
    - name: Clippy (gctc)
      run: cargo clippy --bin gctc --features native,http -- -D warnings
      working-directory: src/rust
    - name: Install for node
      run: yarn install --frozen-lockfile
      working-directory: src/node
    - name: Check typescript
      run: yarn lint
      working-directory: src/node

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
    - name: Run rust tests
      run: cd src/rust && ./scripts/run-tests
